### ISSUE TITLE
UI/UX help

### ISSUE THREAD

**Issue by vchlum** [vchlum/hue-lights-2#1]
Hi @2nv2u !

First, sorry to bother you this way! If you do not have the time, please scroll to the end of this issue only:-) No problem.

I have a courageous question for you. I would like to ask you to share your opinion on UI/UX for this project. I started to implement your idea from hue-lights in this project.

I consider your opinion on this staff valuable. Maybe you would have a better idea, which is not tied by Gnome possibilities... It is obviously in a very early stage. The bridges can be added and the menu loads. It can not change the lights yet, but I would like to do the UI/UX right from the **beginning**. You need to install the QT framework for compilation.

Small sneak peek here:
![Snímek z 2021-11-14 19-42-56](https://user-images.githubusercontent.com/16756616/141695127-af006bf0-dd65-4aee-9746-55d9556c9b89.png)

![Snímek z 2021-11-14 20-20-30](https://user-images.githubusercontent.com/16756616/141695337-59682429-57ef-494b-aeca-abd899691c02.png)

I have also a very important question for you:-D You named your fork of "hue-lights" simply "hue-lite". I like it. Could I steal this name for this project, please?:-)

Vaclav

**Comment by 2nv2u** [comment]
Hi Vaclav, No problem and I gladly help! As you might have noticed though, I'm a bit swamped lately! :)
Considering the UX stuff, I'll think about what could be better out of the Gnome constraints considering QT as base, as for the fork, I did so to make a simplified version of your extension without all the extra options to make it more "lite", I rather keep the name for that for now. As another suggestion, why don't you call this one hue-qt?

**Comment by vchlum** [comment]
Sure, no problem! 'hue-qt' sounds good to me, I like it, thanks. Renamed:-) If you find some time - well, awesome, if not - no worries. This should be leisure time and rest. It is for me:-) So no stress.
